[module]
  [[module.imports]]
    path = "github.com/hugo-fixit/FixIt"
  [[module.imports]]
    path = "github.com/hugo-fixit/component-projects"
  [[module.imports]]
    path = "github.com/hugo-fixit/cmpt-mdevtools"
  [[module.imports]]
    path = "github.com/hugo-fixit/hugo-json-feed"
  [[module.imports]]
    path = "github.com/hugo-fixit/shortcode-caniuse"
  [[module.imports]]
    path = "github.com/hugo-fixit/shortcode-docs-bookmark"
  [[module.imports]]
    path = "github.com/hugo-fixit/shortcode-rewards"
  [module.hugoVersion]
    extended = true
    min = "0.134.1"
