# FixIt 0.3.12 | NEW Custom partials config
# Custom partials must be stored in the /layouts/partials/ directory.
# Depends on open custom blocks https://fixit.lruihao.cn/references/blocks/
[params]
  [params.customPartials]
    head = [
      "inject/component-projects.html",
      "inject/fixit-docs-bookmark.html",
      "inject/shortcode-rewards.html",
    ]
    profile = []
    aside = []
    comment = []
    footer = []
    widgets = []
    assets = [
      "inject/cmpt-mdevtools",
      "inject/cmpt-flyfish",
      "inject/shortcode-caniuse.html",
    ]
    postFooterBefore = []
    postFooterAfter = []

[outputs]
  _merge = "shallow"

[taxonomies]
  _merge = "shallow"

[markup]
  _merge = "shallow"

[module]
  [[module.imports]]
    path = "github.com/hugo-fixit/FixIt"
  [[module.imports]]
    path = "github.com/hugo-fixit/component-projects"
  [[module.imports]]
    path = "github.com/hugo-fixit/cmpt-flyfish"
  [[module.imports]]
    path = "github.com/hugo-fixit/cmpt-mdevtools"
  [[module.imports]]
    path = "github.com/hugo-fixit/hugo-json-feed"
  [[module.imports]]
    path = "github.com/hugo-fixit/shortcode-caniuse"
  [[module.imports]]
    path = "github.com/hugo-fixit/shortcode-docs-bookmark"
  [[module.imports]]
    path = "github.com/hugo-fixit/shortcode-mmt-netease"
  [[module.imports]]
    path = "github.com/hugo-fixit/shortcode-rewards"
  [module.hugoVersion]
    extended = true
    min = "0.134.1"
