# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = 'FixIt Bundle'
license = 'MIT'
licenselink = 'https://github.com/hugo-fixit/fixit-bundle/LICENSE'
description = '🌲 Include FixIt core theme and every FixIt theme components in one bundle component.'
min_version = "0.127.0"

# The home page of the theme, where the source can be found
homepage = 'https://github.com/hugo-fixit/fixit-bundle'

# Taxonomy terms
tags = [
  "blog",
  "clean",
  "responsive",
  "light",
  "dark",
  "theme"
]
features = [
  "i18n",
  "PWA",
  "Sub menu",
  "Content Encryption",
  "watermark",
  "SEO Optimized",
  "friends link template",
  "pagination",
  "syntax-highlighting",
  "cover-image",
  "favicon",
  "social links"
]

# If the theme has a single author
[author]
  name = "Lruihao"
  homepage = "https://lruihao.cn"

