name: Update theme components

# Controls when the workflow will run
on:
  schedule:
    # Update theme components automatically every week
    - cron: "0 0 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Update-FixIt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Update theme components
        run: |
          hugo mod get -u
          hugo mod tidy

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: Cell[bot]
          commit_user_email: lrhx@users.noreply.github.com
          commit_author: Cell[bot] <lrhx@users.noreply.github.com>
          commit_message: ":arrow_up: Chore(deps): update theme components"
